# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instagramClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instagramClone
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'ActiveLabel'
	pod 'Firebase/Messaging'
	pod 'NVActivityIndicatorView'
	pod 'Toast-Swift', '~> 5.0.1'
end
